spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/SA24
          jwk-set-uri: http://keycloak:8080/realms/SA24/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.security: DEBUG

jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: purrfectly_pawsh

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /product-service-doc/v3/api-docs
        name: Product Service